#!/bin/bash
# ================================================================
# TunnelVault — Server installer / upgrader
# Usage: sudo bash install-server.sh [OPTIONS]      (--help for all options)
#
# Examples:
#   sudo bash install-server.sh --domain tunnel.example.com --tls --email ops@example.com
#   sudo bash install-server.sh --upgrade
#   sudo bash install-server.sh --upgrade --auto-update --release-pubkey release-signing.pub
#
# The installer is idempotent. All logic lives in functions; `main` only runs
# when the file is executed (tests source it to exercise the pure helpers).
# ================================================================
set -euo pipefail

# ─── Output helpers ──────────────────────────────────────────────
if [[ -t 1 ]]; then
    RED=$'\033[0;31m'; GREEN=$'\033[0;32m'; YELLOW=$'\033[1;33m'; BLUE=$'\033[0;34m'
    CYAN=$'\033[0;36m'; BOLD=$'\033[1m'; DIM=$'\033[2m'; NC=$'\033[0m'
else
    RED=''; GREEN=''; YELLOW=''; BLUE=''; CYAN=''; BOLD=''; DIM=''; NC=''
fi

TOTAL_STEPS=13
step_num=0
step() {
    step_num=$((step_num + 1))
    echo ""
    echo "${BOLD}${BLUE}[${step_num}/${TOTAL_STEPS}]${NC} ${BOLD}$*${NC}"
    echo "${DIM}────────────────────────────────────────────────────────────${NC}"
}
info()    { echo "  ${GREEN}✓${NC} $*"; }
warn()    { echo "  ${YELLOW}⚠${NC} $*"; }
notice()  { echo "  ${CYAN}ℹ${NC} $*"; }
skipped() { echo "  ${DIM}– $* (skipped)${NC}"; }
fail()    { echo "  ${RED}✗ $*${NC}" >&2; exit 1; }

# ─── Constants ───────────────────────────────────────────────────
INSTALL_DIR="/opt/tunnelvault"
DATA_DIR="${INSTALL_DIR}/data"
LOG_DIR="${INSTALL_DIR}/logs"
USERMGR_SPOOL_DIR="${DATA_DIR}/usermgr"
DEFAULT_DB_PATH="${DATA_DIR}/tunnelvault.db"
ENV_FILE="${INSTALL_DIR}/backend/.env"
VERSION_FILE="${INSTALL_DIR}/VERSION"
SERVICE_NAME="tunnelvault"
SERVICE_USER="tunnelvault"
GW_GROUP="tunnelvault-gw"
SYSTEMD_DIR="/etc/systemd/system"
SSHD_CONF="/etc/ssh/sshd_config"
SUDOERS_FILE="/etc/sudoers.d/tunnelvault"
LOGROTATE_FILE="/etc/logrotate.d/tunnelvault"
CONF_DIR="/etc/tunnelvault"
UPDATE_CONF="${CONF_DIR}/update.conf"
INSTALLED_PUBKEY="${CONF_DIR}/release-signing.pub"
UPDATER_SCRIPT="${INSTALL_DIR}/auto-update.sh"
UPDATER_UNIT="tunnelvault-autoupdate"
UPDATER_LOG="/var/log/tunnelvault-update.log"
# The client's signed updater (install-client.sh) shares CONF_DIR/update.conf on hosts running both
CLIENT_UPDATER_UNIT="tunnelvault-client-autoupdate"
CLIENT_UPDATER_SCRIPT="/opt/tunnelvault-client/auto-update-client.sh"
USERMGR_UNIT="tunnelvault-usermgr"
DEFAULT_UPDATE_REPO="TrainABit/ssh-tunnel"
DEFAULT_UPDATE_SCHEDULE="12h"
NGINX_DIR="/etc/nginx"
ACME_WEBROOT="/var/www/tunnelvault-acme"
LE_LIVE_DIR="/etc/letsencrypt/live"
DEPLOY_HOOK="/etc/letsencrypt/renewal-hooks/deploy/tunnelvault-reload-nginx.sh"
BACKUP_DIR="/var/backups/tunnelvault"
NGINX_MARKER="# Managed by TunnelVault install-server.sh"
NGINX_LEGACY_MARKER="auto-generated by install-server.sh"
GATEWAY_SCRIPTS=(ssh_router.sh gateway-helper.sh manage-user.sh register_token.sh usermgr-worker.sh)
MIN_NODE_MAJOR=20
NODESOURCE_MAJOR=22

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ─── Defaults / state ────────────────────────────────────────────
DOMAIN="tunnel.local";  DOMAIN_SET=false
AUTH_TOKEN="";          AUTH_TOKEN_SET=false
API_PORT=4000;          API_PORT_SET=false
PROXY_PORT=4001;        PROXY_PORT_SET=false
TCP_PORT_MIN=10000
TCP_PORT_MAX=10999
UPGRADE=false
ENABLE_TLS=false
TLS_EMAIL=""
WILDCARD_DIR=""
NO_FIREWALL=false
ASSUME_YES=false
AUTO_UPDATE=""          # "", yes, no
RELEASE_PUBKEY_ARG=""

TLS_MODE="none"         # none | new (--tls) | existing (upgrade of an nginx-fronted install)
TLS_FAILED=false        # --tls requested but not completed (exit code 1)
TLS_OK=false            # nginx serves HTTPS for DOMAIN
START_FAILED=false
ENV_EXISTS=false
GENERATED_AUTH_TOKEN=false
IS_RELEASE=false
SOURCE_VERSION="dev"
NODE_BIN=""
DB_PATH="$DEFAULT_DB_PATH"
FRONTEND_DIST_SRC=""
STAGE_DIR=""
PUBKEY_SOURCE=""
UPDATER_STATE="not installed"
PREVIOUS_DATA_KEY=""

# ================================================================
# Pure helpers (no side effects outside the given files) — unit tested
# ================================================================

usage() {
    cat <<EOF
TunnelVault server installer

Usage: sudo bash install-server.sh [OPTIONS]

General:
  --domain DOMAIN         Server domain (default: tunnel.local; a real domain is required with --tls)
  --auth-token TOKEN      Admin token, 16-256 chars of [A-Za-z0-9._~-] (generated if omitted)
  --port PORT             API / dashboard port (default: 4000)
  --proxy-port PORT       HTTP tunnel proxy port (default: 4001)
  --upgrade               Upgrade an existing installation (keeps database and configuration)
  --yes, -y               Non-interactive: never prompt (used by the auto-updater)
  --no-firewall           Do not touch the firewall (ufw)

TLS (strongly recommended for anything reachable from the internet):
  --tls                   Put nginx + Let's Encrypt in front of TunnelVault. The certificate covers
                          DOMAIN only (HTTP-01 challenge via webroot, renewed automatically).
  --email EMAIL           E-mail address for the Let's Encrypt account (expiry notices)
  --wildcard-cert DIR     Directory with fullchain.pem + privkey.pem of a *.DOMAIN certificate that
                          you obtained separately (DNS-01). Enables HTTPS for HTTP tunnels; without
                          it, HTTP tunnels (*.DOMAIN) are served over plain HTTP on port 80.

Signed automatic updates (settings in /etc/tunnelvault/update.conf, shared with the client):
  --auto-update           Install the auto-updater (verifies signed GitHub releases; needs a public key).
                          Kept on --upgrade.
  --no-auto-update        Remove the auto-updater
  --release-pubkey FILE   Release signing public key (ECDSA P-256 PEM). Default: the installed
                          /etc/tunnelvault/release-signing.pub, else release-signing.pub next to this
                          script. An installed key is only replaced by an explicit --release-pubkey.

  -h, --help              Show this help
EOF
}

is_valid_port() { [[ "${1:-}" =~ ^[1-9][0-9]{0,4}$ ]] && (( $1 <= 65535 )); }

# Hostname with at least two labels (letters, digits, hyphens)
is_valid_domain() {
    local d="${1:-}"
    (( ${#d} <= 253 )) || return 1
    [[ "$d" =~ ^([A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?\.)+[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?$ ]]
}

# Publicly resolvable name suitable for Let's Encrypt (not an IP, not .local etc.)
is_public_domain() {
    local d="${1,,}"
    is_valid_domain "$d" || return 1
    [[ ! "$d" =~ ^[0-9.]+$ ]] || return 1
    case "$d" in
        *.local | *.localhost | localhost | *.internal | *.lan | *.home.arpa | *.test | *.invalid | *.example) return 1 ;;
    esac
    [[ "${d##*.}" =~ ^[a-z][a-z0-9-]*[a-z0-9]$ ]]
}

is_valid_email() {
    local re='^[A-Za-z0-9.!#%&*+/=?^_{|}~-]{1,64}@[A-Za-z0-9]([A-Za-z0-9.-]{0,251}[A-Za-z0-9])?$'
    [[ "${1:-}" =~ $re && "$1" == *@*.* ]]
}

is_valid_auth_token() { [[ "${1:-}" =~ ^[A-Za-z0-9._~-]{16,256}$ ]]; }

# update.conf SCHEDULE -> systemd OnUnitActiveSec (same rule as install-client.sh)
is_valid_schedule() { [[ "${1:-}" =~ ^[1-9][0-9]{0,4}(min|h|d)$ ]]; }

# ENABLED semantics of the updater (auto-update.sh read_conf): 1/true/yes/on
is_enabled_value() { [[ "${1,,}" =~ ^(1|true|yes|on)$ ]]; }

# PEM ECDSA P-256 public key — the only key type the updaters accept (tv_check_pubkey)
is_p256_pubkey() {
    local text
    [[ -f "${1:-}" && -r "$1" ]] || return 1
    text="$(openssl pkey -pubin -in "$1" -noout -text 2>/dev/null)" || return 1
    [[ "$text" == *prime256v1* || "$text" == *P-256* ]]
}

# Absolute path without spaces or characters that are special in nginx/systemd files
is_safe_path() { [[ "${1:-}" =~ ^/[A-Za-z0-9._@+/-]*$ && "$1" != *..* ]]; }

# "v22.3.0" | "22.3.0" -> 22
version_major() { local v="${1#v}"; v="${v%%.*}"; [[ "$v" =~ ^[0-9]+$ ]] && echo "$v"; }

# version_ge A B: true when dotted version A >= B
version_ge() {
    local IFS=.
    local -a a b
    read -r -a a <<< "${1}"
    read -r -a b <<< "${2}"
    local i x y
    for i in 0 1 2 3; do
        x="${a[i]:-0}"; y="${b[i]:-0}"
        x="${x%%[!0-9]*}"; y="${y%%[!0-9]*}"
        x=$((10#${x:-0})); y=$((10#${y:-0}))
        (( x > y )) && return 0
        (( x < y )) && return 1
    done
    return 0
}

random_hex() { openssl rand -hex "${1:-32}"; }

# Value of KEY in an env file (last active assignment; surrounding quotes removed)
env_get() {
    local file="$1" key="$2"
    [[ -f "$file" ]] || return 0
    TV_KEY="$key" awk '
        BEGIN { k = ENVIRON["TV_KEY"]; re = "^[ \t]*(export[ \t]+)?" k "[ \t]*=" }
        $0 ~ re {
            v = $0; sub(/^[^=]*=/, "", v)
            sub(/^[ \t]+/, "", v); sub(/[ \t\r]+$/, "", v)
            q = substr(v, 1, 1)
            if (q != "\"" && q != "\047") sub(/[ \t]+#.*$/, "", v)
            if ((q == "\"" || q == "\047") && length(v) >= 2 && substr(v, length(v), 1) == q) v = substr(v, 2, length(v) - 2)
            val = v; found = 1
        }
        END { if (found) print val }' "$file"
}

# True when KEY has an active (uncommented) assignment
env_has() {
    local file="$1" key="$2"
    [[ -f "$file" ]] && grep -Eq "^[[:space:]]*(export[[:space:]]+)?${key}[[:space:]]*=" "$file"
}

# Set KEY=VALUE: replaces the first active assignment (drops duplicates) or appends.
# Rewrites in place so owner and mode of the file are kept.
env_set() {
    local file="$1" key="$2" value="$3" tmp
    [[ "$key" =~ ^[A-Z][A-Z0-9_]*$ ]] || { echo "env_set: bad key '$key'" >&2; return 1; }
    [[ "$value" != *$'\n'* && "$value" != *$'\r'* ]] || { echo "env_set: multi-line value for $key" >&2; return 1; }
    [[ -f "$file" ]] || : > "$file"
    tmp="$(mktemp "${file}.XXXXXX")"
    TV_KEY="$key" TV_VALUE="$value" awk '
        BEGIN { k = ENVIRON["TV_KEY"]; v = ENVIRON["TV_VALUE"]; re = "^[ \t]*(export[ \t]+)?" k "[ \t]*=" }
        $0 ~ re { if (!done) { print k "=" v; done = 1 } ; next }
        { print }
        END { if (!done) print k "=" v }' "$file" > "$tmp"
    cat "$tmp" > "$file"
    rm -f "$tmp"
}

# Append KEY=VALUE (with an optional comment line) only when KEY is not assigned yet.
# Returns 0 when it was added, 1 when it already existed.
env_ensure() {
    local file="$1" key="$2" value="$3" comment="${4:-}"
    env_has "$file" "$key" && return 1
    if [[ -s "$file" && -n "$(tail -c 1 "$file")" ]]; then echo >> "$file"; fi
    if [[ -n "$comment" ]]; then printf '# %s\n' "$comment" >> "$file"; fi
    env_set "$file" "$key" "$value"
    return 0
}

# Comment out TLS_CERT/TLS_KEY (and TLS_PROXY_*) lines that point into /etc/letsencrypt:
# the service user cannot read them (crash loop) and nginx terminates TLS instead.
# Prints the number of lines changed.
env_disable_letsencrypt_tls() {
    local file="$1" tmp count
    [[ -f "$file" ]] || { echo 0; return 0; }
    tmp="$(mktemp "${file}.XXXXXX")"
    count="$(awk -v out="$tmp" '
        BEGIN { re = "^[ \t]*(export[ \t]+)?TLS_(PROXY_)?(CERT|KEY)[ \t]*=[ \t]*[\"\047]?/etc/letsencrypt/" }
        {
            if ($0 ~ re) { print "# Disabled by install-server.sh (nginx terminates TLS): " $0 > out; n++ }
            else print $0 > out
        }
        END { print n + 0 }' "$file")"
    cat "$tmp" > "$file"
    rm -f "$tmp"
    echo "$count"
}

# Public URL template of HTTP tunnels behind nginx
http_tunnel_template() {
    local domain="$1" wildcard="$2"
    if [[ -n "$wildcard" ]]; then echo "https://{subdomain}.${domain}"; else echo "http://{subdomain}.${domain}"; fi
}

# Fresh .env (values come from the globals set by argument parsing)
render_env_file() {
    local data_key="$1"
    cat <<EOF
# TunnelVault server configuration — generated by install-server.sh on $(date -u '+%Y-%m-%d').
# Every option is documented in backend/.env.example. Keep this file private (0600).
NODE_ENV=production

# Network
PORT=${API_PORT}
PROXY_PORT=${PROXY_PORT}
TCP_PORT_MIN=${TCP_PORT_MIN}
TCP_PORT_MAX=${TCP_PORT_MAX}
DOMAIN=${DOMAIN}
EOF
    if [[ "$TLS_MODE" != "none" ]]; then
        cat <<EOF
# nginx on this host terminates TLS and forwards to 127.0.0.1
BIND_HOST=127.0.0.1
TRUST_PROXY=loopback
PUBLIC_URL=https://${DOMAIN}
HTTP_TUNNEL_URL_TEMPLATE=$(http_tunnel_template "$DOMAIN" "$WILDCARD_DIR")
EOF
    else
        cat <<EOF
# WARNING: no TLS — tokens and passwords cross the network in plaintext.
# Re-run: install-server.sh --upgrade --tls --domain <your-domain>
BIND_HOST=0.0.0.0
# TRUST_PROXY=loopback   # only when a reverse proxy on this host forwards to TunnelVault
# PUBLIC_URL=https://tunnel.example.com
EOF
    fi
    cat <<EOF

# Secrets
AUTH_TOKEN=${AUTH_TOKEN}
# Encrypts SSH private keys stored for the web terminal (AES-256-GCM). Do not lose it.
DATA_ENCRYPTION_KEY=${data_key}

# Data & privacy
DB_PATH=${DB_PATH}
USERMGR_SPOOL_DIR=${USERMGR_SPOOL_DIR}
# GeoIP for sessions: off | maxmind (GEOIP_DB=/path/GeoLite2-City.mmdb) | ip-api (non-commercial, plain HTTP)
GEOIP_PROVIDER=off
# Delete connection sessions (visitor IPs) older than N days (0 = keep forever)
SESSION_RETENTION_DAYS=90

# Logging (levels: debug, info, warn, error)
LOG_LEVEL=info
LOG_FILE=${LOG_DIR}/tunnelvault.log
# LOG_FORMAT=json

# Webhook notifications (optional — fires when tunnels connect/disconnect)
# WEBHOOK_URL=https://ntfy.sh/your-topic
# WEBHOOK_TYPE=ntfy   # ntfy | slack | discord | json (default: json)
EOF
}

render_service_unit() {
    local node_bin="$1"
    cat <<EOF
[Unit]
Description=TunnelVault server (API, dashboard, tunnels)
Documentation=https://github.com/${DEFAULT_UPDATE_REPO}
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${SERVICE_USER}
Group=${SERVICE_USER}
WorkingDirectory=${INSTALL_DIR}/backend
EnvironmentFile=${ENV_FILE}
ExecStart=${node_bin} ${INSTALL_DIR}/backend/src/server.js
Restart=always
RestartSec=5
# Exit code 78 = configuration error (logged once): do not restart in a loop
RestartPreventExitStatus=78
TimeoutStopSec=20
StandardOutput=journal
StandardError=journal
SyslogIdentifier=tunnelvault

# Hardening
UMask=0077
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=yes
ReadWritePaths=${DATA_DIR} ${LOG_DIR}
PrivateTmp=yes
PrivateDevices=yes
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectKernelLogs=yes
ProtectControlGroups=yes
ProtectClock=yes
ProtectHostname=yes
ProtectProc=invisible
RestrictSUIDSGID=yes
RestrictRealtime=yes
RestrictNamespaces=yes
LockPersonality=yes
RemoveIPC=yes
SystemCallArchitectures=native
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6 AF_NETLINK
CapabilityBoundingSet=
AmbientCapabilities=

[Install]
WantedBy=multi-user.target
EOF
}

render_usermgr_path_unit() {
    cat <<EOF
[Unit]
Description=TunnelVault gateway user requests (spool watcher)

[Path]
PathExistsGlob=${USERMGR_SPOOL_DIR}/*.req
Unit=${USERMGR_UNIT}.service

[Install]
WantedBy=multi-user.target
EOF
}

render_usermgr_service_unit() {
    cat <<EOF
[Unit]
Description=TunnelVault gateway user manager (applies queued API requests)
After=local-fs.target

[Service]
Type=oneshot
User=root
# Never add EnvironmentFile=${ENV_FILE}: that file is writable by the service user.
ExecStart=${INSTALL_DIR}/usermgr-worker.sh
TimeoutStartSec=10min
StandardOutput=journal
StandardError=journal
SyslogIdentifier=${USERMGR_UNIT}
NoNewPrivileges=yes
PrivateTmp=yes
PrivateNetwork=yes
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectControlGroups=yes
ProtectClock=yes
ProtectHostname=yes
RestrictRealtime=yes
RestrictSUIDSGID=yes
LockPersonality=yes
SystemCallArchitectures=native
EOF
}

render_updater_service_unit() {
    cat <<EOF
[Unit]
Description=TunnelVault signed auto-updater
Documentation=https://github.com/${DEFAULT_UPDATE_REPO}/releases
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
User=root
ExecStart=${UPDATER_SCRIPT}
TimeoutStartSec=30min
Nice=10
StandardOutput=journal
StandardError=journal
SyslogIdentifier=tunnelvault-update
EOF
}

# SCHEDULE from update.conf ("12h", "30min", "1d") -> OnUnitActiveSec
render_updater_timer_unit() {
    local schedule="${1:-$DEFAULT_UPDATE_SCHEDULE}"
    is_valid_schedule "$schedule" || schedule="$DEFAULT_UPDATE_SCHEDULE"
    cat <<EOF
[Unit]
Description=TunnelVault signed auto-update timer

[Timer]
OnBootSec=15min
OnUnitActiveSec=${schedule}
RandomizedDelaySec=1h
Persistent=true

[Install]
WantedBy=timers.target
EOF
}

render_update_conf() {
    local enabled="$1"
    cat <<EOF
# TunnelVault auto-update settings (read by auto-update.sh / auto-update-client.sh;
# shared by the server and client updaters when both are installed on this host).
# Releases are installed only if SHA256SUMS.sig verifies with PUBKEY and the tarball
# matches SHA256SUMS; downgrades are refused. ENABLED=0 pauses the updater(s);
# PINNED_VERSION (e.g. 2.0.1) pins a release, empty = latest. SCHEDULE is applied
# to the systemd timer(s) by the installers (re-run with --upgrade after editing).
ENABLED=${enabled}
SCHEDULE=${DEFAULT_UPDATE_SCHEDULE}
UPDATE_REPO=${DEFAULT_UPDATE_REPO}
PINNED_VERSION=
PUBKEY=${INSTALLED_PUBKEY}
EOF
}

render_deploy_hook() {
    cat <<'EOF'
#!/bin/sh
# Installed by TunnelVault install-server.sh: reload nginx after a Let's Encrypt
# renewal so that the new certificate is served.
if command -v nginx >/dev/null 2>&1 && nginx -t -q; then
    systemctl try-reload-or-restart nginx
fi
EOF
}

render_logrotate() {
    cat <<EOF
# Installed by TunnelVault install-server.sh
${LOG_DIR}/*.log {
    daily
    rotate 14
    maxsize 50M
    missingok
    notifempty
    compress
    delaycompress
    copytruncate
    su ${SERVICE_USER} ${SERVICE_USER}
}
EOF
}

render_sshd_block() {
    cat <<EOF
# === TUNNELVAULT-GATEWAY START ===
# Legacy SSH gateway (managed by install-server.sh): gw-<token> users can only
# run the TunnelVault router, which relays them to their configured target.
Match User "gw-*"
    ForceCommand ${INSTALL_DIR}/ssh_router.sh
    AuthenticationMethods publickey
    PermitTTY no
    X11Forwarding no
    AllowAgentForwarding no
    AllowTcpForwarding no
    AllowStreamLocalForwarding no
    PermitTunnel no
    GatewayPorts no
    PermitUserRC no
Match all
# === TUNNELVAULT-GATEWAY END ===
EOF
}

# sshd_config content with the TunnelVault block (re)placed at the end
sshd_config_with_block() {
    local file="$1"
    awk '
        /^# === TUNNELVAULT-GATEWAY START ===/ { skip = 1; next }
        /^# === TUNNELVAULT-GATEWAY END ===/   { skip = 0; next }
        !skip { lines[++n] = $0 }
        END {
            while (n > 0 && lines[n] ~ /^[ \t]*$/) n--
            for (i = 1; i <= n; i++) print lines[i]
        }' "$file"
    echo ""
    render_sshd_block
}

# ─── nginx ───────────────────────────────────────────────────────
# Globals used: LE_LIVE_DIR, ACME_WEBROOT, NGINX_MARKER
_nginx_listen() {
    local port="$1" ssl="$2" ipv6="$3" http2_directive="$4" suffix=""
    if [[ "$ssl" == 1 ]]; then
        suffix=" ssl"
        [[ "$http2_directive" == 1 ]] || suffix+=" http2"
    fi
    echo "    listen ${port}${suffix};"
    if [[ "$ipv6" == 1 ]]; then echo "    listen [::]:${port}${suffix};"; fi
    if [[ "$ssl" == 1 && "$http2_directive" == 1 ]]; then echo "    http2 on;"; fi
}

_nginx_tls() {
    local cert_dir="$1"
    cat <<EOF
    ssl_certificate     ${cert_dir}/fullchain.pem;
    ssl_certificate_key ${cert_dir}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305;
    ssl_prefer_server_ciphers off;
    ssl_session_timeout 1d;
    ssl_session_cache shared:TunnelVaultTLS:10m;
    ssl_session_tickets off;
EOF
}

# Headers are set once per server block: a proxy_set_header inside a location
# would silently drop all inherited ones.
_nginx_proxy_headers() {
    cat <<'EOF'
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $tunnelvault_connection_upgrade;
EOF
}

_nginx_acme_location() {
    cat <<EOF
    location ^~ /.well-known/acme-challenge/ {
        root ${ACME_WEBROOT};
        default_type text/plain;
    }
EOF
}

_nginx_tunnel_location() {
    local proxy_port="$1"
    cat <<EOF
    # HTTP tunnels: streamed in both directions, WebSockets pass through
    client_max_body_size 100m;
    location / {
        proxy_pass http://127.0.0.1:${proxy_port};
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_read_timeout 1h;
        proxy_send_timeout 1h;
    }
EOF
}

# render_nginx_conf MODE DOMAIN API_PORT PROXY_PORT WILDCARD_DIR IPV6(0|1) HTTP2_DIRECTIVE(0|1)
#   MODE=acme : HTTP only, serves ACME challenges for DOMAIN (before a certificate exists)
#   MODE=https: final configuration
render_nginx_conf() {
    local mode="$1" domain="$2" api_port="$3" proxy_port="$4" wildcard="$5" ipv6="$6" h2="$7"
    cat <<EOF
${NGINX_MARKER} (regenerated on --upgrade).
# Delete the line above to keep local changes; the installer then leaves this file alone.
# tunnelvault-domain: ${domain}
# tunnelvault-wildcard-cert: ${wildcard:-none}

map \$http_upgrade \$tunnelvault_connection_upgrade {
    default upgrade;
    ''      close;
}

EOF
    if [[ "$mode" == "acme" ]]; then
        cat <<EOF
# Temporary: only answers Let's Encrypt HTTP-01 challenges until the certificate exists
server {
$(_nginx_listen 80 0 "$ipv6" "$h2")
    server_name ${domain};
    server_tokens off;
$(_nginx_acme_location)
    location / {
        return 503;
    }
}
EOF
        return 0
    fi

    cat <<EOF
# HTTP: ACME challenges (renewals) and redirect to HTTPS
server {
$(_nginx_listen 80 0 "$ipv6" "$h2")
    server_name ${domain};
    server_tokens off;
$(_nginx_acme_location)
    location / {
        return 301 https://\$host\$request_uri;
    }
}

# Dashboard, API, device WebSocket (/ws) and web terminal (/ws/ssh)
server {
$(_nginx_listen 443 1 "$ipv6" "$h2")
    server_name ${domain};
    server_tokens off;
$(_nginx_tls "${LE_LIVE_DIR}/${domain}")

    client_max_body_size 2m;
$(_nginx_proxy_headers)

    location / {
        proxy_pass http://127.0.0.1:${api_port};
    }
    location ^~ /ws/ssh {
        proxy_pass http://127.0.0.1:${api_port};
        proxy_buffering off;
        proxy_read_timeout 1d;
        proxy_send_timeout 1d;
    }
    location ^~ /ws {
        proxy_pass http://127.0.0.1:${api_port};
        proxy_buffering off;
        proxy_read_timeout 1d;
        proxy_send_timeout 1d;
    }
}

EOF
    if [[ -n "$wildcard" ]]; then
        cat <<EOF
# HTTP tunnels on *.${domain}: redirect to HTTPS
server {
$(_nginx_listen 80 0 "$ipv6" "$h2")
    server_name *.${domain};
    server_tokens off;
    location / {
        return 301 https://\$host\$request_uri;
    }
}

# HTTP tunnels on *.${domain} (wildcard certificate: ${wildcard})
server {
$(_nginx_listen 443 1 "$ipv6" "$h2")
    server_name *.${domain};
    server_tokens off;
$(_nginx_tls "$wildcard")

$(_nginx_proxy_headers)
$(_nginx_tunnel_location "$proxy_port")
}
EOF
    else
        cat <<EOF
# HTTP tunnels on *.${domain} over plain HTTP (no wildcard certificate configured;
# obtain one via DNS-01 and re-run with --wildcard-cert DIR to enable HTTPS)
server {
$(_nginx_listen 80 0 "$ipv6" "$h2")
    server_name *.${domain};
    server_tokens off;
$(_nginx_proxy_headers)
$(_nginx_tunnel_location "$proxy_port")
}
EOF
    fi
}

# Is this nginx site file generated by us (current or v1 installer)?
nginx_conf_is_ours() {
    local file="$1"
    [[ -f "$file" ]] || return 1
    head -n 3 "$file" | grep -Fq -e "$NGINX_MARKER" -e "$NGINX_LEGACY_MARKER"
}

# Wildcard certificate directory recorded in our nginx file ("" when none)
nginx_conf_wildcard_dir() {
    local file="$1" dir
    [[ -f "$file" ]] || return 0
    dir="$(sed -n 's/^# tunnelvault-wildcard-cert: //p' "$file" | head -n 1)"
    if [[ "$dir" != "none" ]] && is_safe_path "$dir"; then echo "$dir"; fi
}

# The old (unsigned, git pull as root) updater of TunnelVault 1.x?
is_legacy_updater() {
    local file="$1"
    [[ -f "$file" ]] && grep -Eq '^SOURCE_DIR=|git pull origin|__SOURCE_DIR__' "$file"
}

# ================================================================
# System actions
# ================================================================

# write_file DEST MODE OWNER < content — atomic replace (running scripts keep
# their old inode), returns 0 when the content changed.
write_file() {
    local dest="$1" mode="$2" owner="$3" tmp dir
    dir="$(dirname "$dest")"
    mkdir -p "$dir"
    tmp="$(mktemp "${dir}/.$(basename "$dest").XXXXXX")"
    cat > "$tmp"
    chmod "$mode" "$tmp"
    chown "$owner" "$tmp"
    if [[ -f "$dest" && ! -L "$dest" ]] && cmp -s "$tmp" "$dest"; then
        chmod "$mode" "$dest"; chown "$owner" "$dest"
        rm -f "$tmp"
        return 1
    fi
    mv -f "$tmp" "$dest"
    return 0
}

# chown only regular files/dirs that are not symlinks and not hard-linked
# (the data directory is writable by the service user).
safe_chown() {
    local owner="$1" path="$2"
    [[ -e "$path" && ! -L "$path" ]] || return 0
    if [[ -f "$path" && "$(stat -c %h "$path")" != "1" ]]; then
        warn "Not changing owner of hard-linked file ${path}"
        return 0
    fi
    chown "$owner" "$path"
}

apt_install() {
    local missing=() pkg
    for pkg in "$@"; do
        if dpkg -s "$pkg" >/dev/null 2>&1; then skipped "$pkg already installed"; else missing+=("$pkg"); fi
    done
    (( ${#missing[@]} )) || return 0
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq "${missing[@]}" >/dev/null
    info "Installed: ${missing[*]}"
}

confirm() {
    local prompt="$1" answer
    $ASSUME_YES && return 0
    read -r -p "  ${prompt} [y/N] " answer || return 1
    [[ "${answer,,}" == "y" || "${answer,,}" == "yes" ]]
}

print_plaintext_warning() {
    echo ""
    echo "${RED}${BOLD}  ┌──────────────────────────────────────────────────────────────────┐"
    echo "  │  WARNING: TunnelVault is being installed WITHOUT TLS.             │"
    echo "  │  The admin token, device tokens and web-terminal SSH passwords    │"
    echo "  │  will cross the network in PLAINTEXT (http:// and ws://).         │"
    echo "  │  For any internet-facing server use:                              │"
    echo "  │    --tls --domain <your-domain> [--email you@example.com]         │"
    echo "  └──────────────────────────────────────────────────────────────────┘${NC}"
    echo ""
}

_need_arg() { [[ $# -ge 2 && -n "$2" ]] || fail "Option $1 requires a value"; }

parse_args() {
    local need=_need_arg
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --domain)         $need "$@"; DOMAIN="${2,,}"; DOMAIN_SET=true; shift 2 ;;
            --auth-token)     $need "$@"; AUTH_TOKEN="$2"; AUTH_TOKEN_SET=true; shift 2 ;;
            --port)           $need "$@"; API_PORT="$2"; API_PORT_SET=true; shift 2 ;;
            --proxy-port)     $need "$@"; PROXY_PORT="$2"; PROXY_PORT_SET=true; shift 2 ;;
            --email)          $need "$@"; TLS_EMAIL="$2"; shift 2 ;;
            --wildcard-cert)  $need "$@"; WILDCARD_DIR="${2%/}"; shift 2 ;;
            --release-pubkey) $need "$@"; RELEASE_PUBKEY_ARG="$2"; shift 2 ;;
            --upgrade)        UPGRADE=true; shift ;;
            --tls)            ENABLE_TLS=true; shift ;;
            --no-firewall)    NO_FIREWALL=true; shift ;;
            --auto-update)    AUTO_UPDATE="yes"; shift ;;
            --no-auto-update) AUTO_UPDATE="no"; shift ;;
            -y|--yes)         ASSUME_YES=true; shift ;;
            -h|--help)        usage; exit 0 ;;
            *)                echo "Unknown option: $1 (see --help)" >&2; exit 1 ;;
        esac
    done

    if $DOMAIN_SET && ! is_valid_domain "$DOMAIN"; then fail "Invalid --domain '${DOMAIN}'"; fi
    if $AUTH_TOKEN_SET && ! is_valid_auth_token "$AUTH_TOKEN"; then
        fail "--auth-token must be 16-256 characters of A-Z a-z 0-9 . _ ~ -"
    fi
    is_valid_port "$API_PORT"   || fail "Invalid --port '${API_PORT}'"
    is_valid_port "$PROXY_PORT" || fail "Invalid --proxy-port '${PROXY_PORT}'"
    if [[ -n "$TLS_EMAIL" ]] && ! is_valid_email "$TLS_EMAIL"; then fail "Invalid --email '${TLS_EMAIL}'"; fi
    if [[ -n "$WILDCARD_DIR" ]]; then
        is_safe_path "$WILDCARD_DIR" || fail "--wildcard-cert must be an absolute path without spaces or special characters"
        $ENABLE_TLS || fail "--wildcard-cert requires --tls"
    fi
    if [[ -n "$TLS_EMAIL" ]] && ! $ENABLE_TLS; then fail "--email is only used with --tls"; fi
}

# ─── Step 1: pre-flight ──────────────────────────────────────────
preflight() {
    [[ $EUID -eq 0 ]] || fail "This script must be run as root. Use: sudo bash install-server.sh"
    info "Running as root"
    command -v apt-get >/dev/null 2>&1 || fail "This installer requires Debian/Ubuntu (apt-get not found)"
    command -v systemctl >/dev/null 2>&1 || fail "systemd is required"
    info "Debian/Ubuntu with systemd detected"

    local f
    for f in backend/src/server.js backend/src/database.js backend/package.json backend/package-lock.json \
             "${GATEWAY_SCRIPTS[@]/#/gateway/}" gateway/tunnelvault-sudoers; do
        [[ -f "${SCRIPT_DIR}/${f}" ]] || fail "Missing ${f} next to this script (${SCRIPT_DIR}). Run it from the project root."
    done
    if [[ -f "${SCRIPT_DIR}/VERSION" ]]; then
        local v
        v="$(tr -d '[:space:]' < "${SCRIPT_DIR}/VERSION")"
        if [[ "$v" =~ ^[0-9A-Za-z.+_-]{1,64}$ ]]; then SOURCE_VERSION="$v"; fi
    fi
    # A release package ships VERSION + a prebuilt dashboard and is not a git checkout
    # (a checkout may contain a stale local build, so it is always rebuilt).
    if [[ -f "${SCRIPT_DIR}/VERSION" && -f "${SCRIPT_DIR}/frontend/dist/index.html" && ! -e "${SCRIPT_DIR}/.git" ]]; then
        IS_RELEASE=true
        info "Release package ${SOURCE_VERSION} (prebuilt dashboard)"
    else
        info "Source tree at ${SCRIPT_DIR} (version: ${SOURCE_VERSION})"
    fi

    # Existing installation? The .env file belongs to the service user: never follow a
    # symlink or hard link there as root.
    if [[ -L "$ENV_FILE" ]] || { [[ -e "$ENV_FILE" ]] && { [[ ! -f "$ENV_FILE" ]] || [[ "$(stat -c %h "$ENV_FILE")" != "1" ]]; }; }; then
        fail "${ENV_FILE} is not a regular file (symlink or hard link?) — refusing to use it"
    fi
    if [[ -f "$ENV_FILE" ]]; then ENV_EXISTS=true; fi
    if $UPGRADE && [[ ! -d "${INSTALL_DIR}/backend" ]]; then
        warn "No existing installation found — performing a fresh install instead"
        UPGRADE=false
    fi
    if ! $UPGRADE && $ENV_EXISTS; then
        warn "Existing TunnelVault installation detected at ${INSTALL_DIR}"
        if $ASSUME_YES; then
            fail "Refusing to overwrite the existing configuration non-interactively. Use --upgrade."
        fi
        echo "  ${YELLOW}To upgrade without losing data, run: ${BOLD}sudo bash install-server.sh --upgrade${NC}"
        confirm "Continue with a fresh install? This REPLACES the configuration (a backup is kept)." \
            || { echo "  ${DIM}Aborted.${NC}"; exit 0; }
    fi
    if $UPGRADE; then
        info "Upgrade: database and configuration are preserved"
    fi

    # Values of an existing configuration (validated: the file is writable by the service user)
    if $ENV_EXISTS; then
        local v
        if ! $DOMAIN_SET; then
            v="$(env_get "$ENV_FILE" DOMAIN)"
            if [[ -n "$v" ]]; then
                is_valid_domain "$v" || fail "Invalid DOMAIN in ${ENV_FILE}"
                DOMAIN="${v,,}"
            fi
        fi
        if ! $API_PORT_SET; then
            v="$(env_get "$ENV_FILE" PORT)"
            if [[ -n "$v" ]]; then
                is_valid_port "$v" || fail "Invalid PORT in ${ENV_FILE}"
                API_PORT="$v"
            fi
        fi
        if ! $PROXY_PORT_SET; then
            v="$(env_get "$ENV_FILE" PROXY_PORT)"
            if [[ -n "$v" ]]; then
                is_valid_port "$v" || fail "Invalid PROXY_PORT in ${ENV_FILE}"
                PROXY_PORT="$v"
            fi
        fi
        v="$(env_get "$ENV_FILE" TCP_PORT_MIN)"; if is_valid_port "$v"; then TCP_PORT_MIN="$v"; fi
        v="$(env_get "$ENV_FILE" TCP_PORT_MAX)"; if is_valid_port "$v"; then TCP_PORT_MAX="$v"; fi
        v="$(env_get "$ENV_FILE" DB_PATH)"
        if [[ -n "$v" ]]; then
            if is_safe_path "$v" && [[ "$v" == "${DATA_DIR}/"* ]]; then
                DB_PATH="$v"
            else
                warn "DB_PATH=${v} is outside ${DATA_DIR}; the hardened service can only write to ${DATA_DIR}."
                warn "Using ${DEFAULT_DB_PATH} for initialisation — move the database or adjust the unit manually."
            fi
        fi
        if ! $UPGRADE; then
            # fresh install over an existing one: keep the encryption key of the kept database
            PREVIOUS_DATA_KEY="$(env_get "$ENV_FILE" DATA_ENCRYPTION_KEY)"
        fi
    fi
    (( TCP_PORT_MIN <= TCP_PORT_MAX )) || fail "TCP_PORT_MIN must not exceed TCP_PORT_MAX"
    [[ "$API_PORT" != "$PROXY_PORT" ]] || fail "--port and --proxy-port must differ"
    local p
    for p in "$API_PORT" "$PROXY_PORT"; do
        if (( p >= TCP_PORT_MIN && p <= TCP_PORT_MAX )); then
            fail "Port ${p} lies inside the TCP tunnel range ${TCP_PORT_MIN}-${TCP_PORT_MAX}"
        fi
    done

    # TLS mode
    local site_file
    site_file="$(nginx_site_file)"
    if $ENABLE_TLS; then
        TLS_MODE="new"
        if $UPGRADE && [[ -z "$WILDCARD_DIR" ]] && nginx_conf_is_ours "$site_file"; then
            WILDCARD_DIR="$(nginx_conf_wildcard_dir "$site_file")"
        fi
    elif $UPGRADE && nginx_conf_is_ours "$site_file"; then
        TLS_MODE="existing"
        WILDCARD_DIR="$(nginx_conf_wildcard_dir "$site_file")"
    fi
    if [[ "$TLS_MODE" != "none" ]]; then
        is_public_domain "$DOMAIN" \
            || fail "TLS needs a public domain name pointing to this server (got '${DOMAIN}'). Use --domain."
        if [[ -n "$WILDCARD_DIR" ]]; then
            [[ -f "${WILDCARD_DIR}/fullchain.pem" && -f "${WILDCARD_DIR}/privkey.pem" ]] \
                || fail "Wildcard certificate not found: ${WILDCARD_DIR}/fullchain.pem and privkey.pem are required"
            if command -v openssl >/dev/null 2>&1 \
                && ! openssl x509 -in "${WILDCARD_DIR}/fullchain.pem" -noout -text 2>/dev/null | grep -Fq "DNS:*.${DOMAIN}"; then
                warn "The certificate in ${WILDCARD_DIR} does not seem to cover *.${DOMAIN}"
            fi
        fi
        if [[ "$TLS_MODE" == "new" && -f "$site_file" ]] && ! nginx_conf_is_ours "$site_file"; then
            fail "${site_file} exists and was not created by this installer. Move it away and re-run."
        fi
        info "TLS: nginx terminates HTTPS for ${DOMAIN}"
    fi

    # Auto-update opt-in needs a public key
    if [[ "$AUTO_UPDATE" == "yes" ]]; then
        resolve_pubkey_source
        [[ -n "$PUBKEY_SOURCE" ]] \
            || fail "--auto-update needs the release public key: --release-pubkey FILE (or release-signing.pub next to this script)"
        [[ -f "${SCRIPT_DIR}/auto-update.sh" ]] || fail "auto-update.sh is missing next to this script"
        is_legacy_updater "${SCRIPT_DIR}/auto-update.sh" \
            && fail "${SCRIPT_DIR}/auto-update.sh is the old unsigned updater — use a current release"
    elif [[ -n "$RELEASE_PUBKEY_ARG" ]]; then
        resolve_pubkey_source
    fi
    if [[ -n "$PUBKEY_SOURCE" ]]; then
        is_p256_pubkey "$PUBKEY_SOURCE" \
            || fail "${PUBKEY_SOURCE} is not an ECDSA P-256 public key (PEM) — the updater only accepts P-256 release keys"
    fi
}

nginx_site_file() {
    if [[ -d "${NGINX_DIR}/sites-available" || ! -d "${NGINX_DIR}/conf.d" ]]; then
        echo "${NGINX_DIR}/sites-available/tunnelvault"
    else
        echo "${NGINX_DIR}/conf.d/tunnelvault.conf"
    fi
}

resolve_pubkey_source() {
    PUBKEY_SOURCE=""
    if [[ -n "$RELEASE_PUBKEY_ARG" ]]; then
        [[ -f "$RELEASE_PUBKEY_ARG" ]] || fail "Release public key not found: ${RELEASE_PUBKEY_ARG}"
        PUBKEY_SOURCE="$(cd "$(dirname "$RELEASE_PUBKEY_ARG")" && pwd)/$(basename "$RELEASE_PUBKEY_ARG")"
    elif [[ -f "$INSTALLED_PUBKEY" ]]; then
        PUBKEY_SOURCE="$INSTALLED_PUBKEY"
    elif [[ -f "${SCRIPT_DIR}/release-signing.pub" ]]; then
        PUBKEY_SOURCE="${SCRIPT_DIR}/release-signing.pub"
    fi
}

# ─── Step 3: Node.js ─────────────────────────────────────────────
ensure_node() {
    local major=""
    if command -v node >/dev/null 2>&1; then major="$(version_major "$(node -v 2>/dev/null)" || true)"; fi
    if [[ -n "$major" ]] && (( major >= MIN_NODE_MAJOR )); then
        info "Node.js $(node -v) found (>= ${MIN_NODE_MAJOR}) — keeping it"
    else
        if [[ -n "$major" ]]; then
            warn "Node.js $(node -v) is too old — upgrading to ${NODESOURCE_MAJOR}.x (NodeSource)"
        else
            info "Installing Node.js ${NODESOURCE_MAJOR}.x (NodeSource)"
        fi
        mkdir -p /etc/apt/keyrings
        curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key \
            | gpg --dearmor --yes -o /etc/apt/keyrings/nodesource.gpg
        chmod 0644 /etc/apt/keyrings/nodesource.gpg
        echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${NODESOURCE_MAJOR}.x nodistro main" \
            > /etc/apt/sources.list.d/nodesource.list
        apt-get update -qq >/dev/null
        DEBIAN_FRONTEND=noninteractive apt-get install -y -qq nodejs >/dev/null
        hash -r
        major="$(version_major "$(node -v 2>/dev/null)" || true)"
        if [[ -z "$major" ]] || (( major < MIN_NODE_MAJOR )); then fail "Node.js installation failed"; fi
        info "Node.js $(node -v) installed"
    fi
    command -v npm >/dev/null 2>&1 || fail "npm not found (it ships with the NodeSource nodejs package)"
    info "npm $(npm -v) available"
    NODE_BIN="$(command -v node)"
    case "$NODE_BIN" in
        /home/* | /root/* | /tmp/* | /var/tmp/* | /run/user/*)
            fail "node resolves to ${NODE_BIN}, which the hardened service cannot use. Install a system-wide Node.js >= ${MIN_NODE_MAJOR}." ;;
    esac
    is_safe_path "$NODE_BIN" || fail "Unsupported node path: ${NODE_BIN}"
}

# ─── Step 4: users ───────────────────────────────────────────────
ensure_users() {
    if id "$SERVICE_USER" >/dev/null 2>&1; then
        skipped "User '${SERVICE_USER}' already exists"
    else
        useradd --system --shell /usr/sbin/nologin --home-dir "$INSTALL_DIR" --no-create-home "$SERVICE_USER"
        info "System user '${SERVICE_USER}' created"
    fi
    if getent group "$GW_GROUP" >/dev/null 2>&1; then
        skipped "Group '${GW_GROUP}' already exists"
    else
        groupadd --system "$GW_GROUP"
        info "Group '${GW_GROUP}' created (legacy SSH gateway users)"
    fi
}

# ─── Step 5: build into a staging directory (the running install is untouched) ─
npm_ci_production() {
    (cd "$1" && npm ci --omit=dev --no-audit --no-fund --loglevel=error)
}

prepare_application() {
    mkdir -p "$INSTALL_DIR"
    chown root:root "$INSTALL_DIR"
    chmod 0755 "$INSTALL_DIR"
    STAGE_DIR="${INSTALL_DIR}/.staging"
    rm -rf "$STAGE_DIR"
    mkdir -p "${STAGE_DIR}/backend" "${STAGE_DIR}/frontend"

    cp -R "${SCRIPT_DIR}/backend/src" "${STAGE_DIR}/backend/src"
    cp "${SCRIPT_DIR}/backend/package.json" "${SCRIPT_DIR}/backend/package-lock.json" "${STAGE_DIR}/backend/"
    echo "  ${DIM}Installing backend dependencies (npm ci --omit=dev)...${NC}"
    if ! npm_ci_production "${STAGE_DIR}/backend"; then
        warn "npm ci failed — installing build tools for native modules and retrying"
        apt_install build-essential python3
        rm -rf "${STAGE_DIR}/backend/node_modules"
        npm_ci_production "${STAGE_DIR}/backend" || fail "npm ci failed — the running installation was not changed"
    fi
    (cd "${STAGE_DIR}/backend" && "$NODE_BIN" -e "require('better-sqlite3'); require('ws'); require('express')") \
        || fail "Backend dependencies are not loadable — the running installation was not changed"
    info "Backend prepared"

    FRONTEND_DIST_SRC=""
    if $IS_RELEASE; then
        FRONTEND_DIST_SRC="${SCRIPT_DIR}/frontend/dist"
        info "Using the prebuilt dashboard of the release"
    elif [[ "${TUNNELVAULT_UPDATER:-}" == 1 ]]; then
        # Unattended runs never execute the frontend toolchain's install scripts as root:
        # signed releases ship frontend/dist.
        warn "This package has no prebuilt dashboard (frontend/dist) — keeping the installed one"
    elif [[ -f "${SCRIPT_DIR}/frontend/package.json" ]]; then
        echo "  ${DIM}Building the dashboard (npm ci && npm run build)...${NC}"
        if (cd "${SCRIPT_DIR}/frontend" && npm ci --no-audit --no-fund --loglevel=error && npm run build --silent); then
            FRONTEND_DIST_SRC="${SCRIPT_DIR}/frontend/dist"
            info "Dashboard built"
        else
            warn "Dashboard build failed — keeping the currently installed dashboard (if any)"
        fi
    fi
    if [[ -n "$FRONTEND_DIST_SRC" && -f "${FRONTEND_DIST_SRC}/index.html" ]]; then
        cp -R "$FRONTEND_DIST_SRC" "${STAGE_DIR}/frontend/dist"
    else
        FRONTEND_DIST_SRC=""
        [[ -f "${INSTALL_DIR}/frontend/dist/index.html" ]] || warn "No dashboard build available — the dashboard UI will be missing"
    fi
}

# ─── Step 6: install files ───────────────────────────────────────
swap_in_application() {
    local trash="${INSTALL_DIR}/.previous" item
    rm -rf "$trash"
    mkdir -p "${trash}/backend" "${trash}/frontend" "${INSTALL_DIR}/backend" "${INSTALL_DIR}/frontend"
    for item in src node_modules package.json package-lock.json; do
        if [[ -e "${INSTALL_DIR}/backend/${item}" || -L "${INSTALL_DIR}/backend/${item}" ]]; then
            mv "${INSTALL_DIR}/backend/${item}" "${trash}/backend/${item}"
        fi
        mv "${STAGE_DIR}/backend/${item}" "${INSTALL_DIR}/backend/${item}"
    done
    if [[ -d "${STAGE_DIR}/frontend/dist" ]]; then
        if [[ -e "${INSTALL_DIR}/frontend/dist" ]]; then mv "${INSTALL_DIR}/frontend/dist" "${trash}/frontend/dist"; fi
        mv "${STAGE_DIR}/frontend/dist" "${INSTALL_DIR}/frontend/dist"
    fi
    rm -rf "$trash" "$STAGE_DIR"

    # Application code is root-owned and read-only for the service
    chown -R root:root "${INSTALL_DIR}/backend/src" "${INSTALL_DIR}/backend/node_modules" \
        "${INSTALL_DIR}/backend/package.json" "${INSTALL_DIR}/backend/package-lock.json" "${INSTALL_DIR}/frontend"
    chmod -R u=rwX,go=rX "${INSTALL_DIR}/backend/src" "${INSTALL_DIR}/backend/node_modules" "${INSTALL_DIR}/frontend"
    chmod 0644 "${INSTALL_DIR}/backend/package.json" "${INSTALL_DIR}/backend/package-lock.json"
    chown root:root "${INSTALL_DIR}/backend"
    chmod 0755 "${INSTALL_DIR}/backend" "${INSTALL_DIR}/frontend"
    printf '%s\n' "$SOURCE_VERSION" | write_file "$VERSION_FILE" 0644 root:root || true
    info "Application files installed (version ${SOURCE_VERSION})"
}

install_gateway_files() {
    local script
    for script in "${GATEWAY_SCRIPTS[@]}"; do
        write_file "${INSTALL_DIR}/${script}" 0755 root:root < "${SCRIPT_DIR}/gateway/${script}" || true
    done
    info "Gateway scripts installed: ${GATEWAY_SCRIPTS[*]}"

    # sudoers: validate before it goes live (a broken file would disable sudo)
    local tmp
    tmp="$(mktemp)"
    cat "${SCRIPT_DIR}/gateway/tunnelvault-sudoers" > "$tmp"
    if command -v visudo >/dev/null 2>&1 && ! visudo -c -q -f "$tmp" >/dev/null 2>&1; then
        rm -f "$tmp"
        fail "gateway/tunnelvault-sudoers failed validation (visudo -c)"
    fi
    mkdir -p "$(dirname "$SUDOERS_FILE")"
    write_file "$SUDOERS_FILE" 0440 root:root < "$tmp" || true
    rm -f "$tmp"
    info "Sudoers rule installed (${GW_GROUP} -> gateway-helper.sh as ${SERVICE_USER}; the service has no sudo rights)"

    render_logrotate | write_file "$LOGROTATE_FILE" 0644 root:root || true
}

# ─── Step 7: configuration ───────────────────────────────────────
configure_env() {
    local ts
    ts="$(date -u '+%Y%m%d-%H%M%S')"
    if $ENV_EXISTS; then
        mkdir -p "$BACKUP_DIR"; chmod 0700 "$BACKUP_DIR"
        cp -p "$ENV_FILE" "${BACKUP_DIR}/env.${ts}"
        chmod 0600 "${BACKUP_DIR}/env.${ts}"
        info "Previous configuration backed up to ${BACKUP_DIR}/env.${ts}"
    fi

    if $UPGRADE && $ENV_EXISTS; then
        info "Preserving existing configuration at ${ENV_FILE}"
        $DOMAIN_SET     && env_set "$ENV_FILE" DOMAIN "$DOMAIN"         && notice "DOMAIN set to ${DOMAIN}"
        $API_PORT_SET   && env_set "$ENV_FILE" PORT "$API_PORT"         && notice "PORT set to ${API_PORT}"
        $PROXY_PORT_SET && env_set "$ENV_FILE" PROXY_PORT "$PROXY_PORT" && notice "PROXY_PORT set to ${PROXY_PORT}"
        if $AUTH_TOKEN_SET; then
            env_set "$ENV_FILE" AUTH_TOKEN "$AUTH_TOKEN"
            notice "AUTH_TOKEN replaced (existing dashboard sessions are logged out)"
        fi
        env_ensure "$ENV_FILE" NODE_ENV production || true
        env_ensure "$ENV_FILE" DB_PATH "$DB_PATH" || true
        env_ensure "$ENV_FILE" USERMGR_SPOOL_DIR "$USERMGR_SPOOL_DIR" \
            "Legacy SSH gateway: Linux user requests are queued here (tunnelvault-usermgr.path)" \
            && info "USERMGR_SPOOL_DIR added"
        env_ensure "$ENV_FILE" GEOIP_PROVIDER off \
            "GeoIP for sessions: off | maxmind (GEOIP_DB=/path/GeoLite2-City.mmdb) | ip-api (non-commercial, plain HTTP)" \
            && notice "GEOIP_PROVIDER=off added (visitor IPs are no longer sent to ip-api.com)"
        env_ensure "$ENV_FILE" SESSION_RETENTION_DAYS 90 \
            "Delete connection sessions (visitor IPs) older than N days (0 = keep forever)" \
            && info "SESSION_RETENTION_DAYS=90 added"
        if [[ -z "$(env_get "$ENV_FILE" DATA_ENCRYPTION_KEY)" && -z "$(env_get "$ENV_FILE" DATA_ENCRYPTION_KEY_FILE)" ]]; then
            if env_has "$ENV_FILE" DATA_ENCRYPTION_KEY; then
                env_set "$ENV_FILE" DATA_ENCRYPTION_KEY "$(random_hex 32)"
            else
                env_ensure "$ENV_FILE" DATA_ENCRYPTION_KEY "$(random_hex 32)" \
                    "Encrypts SSH private keys stored for the web terminal (AES-256-GCM). Do not lose it." || true
            fi
            info "DATA_ENCRYPTION_KEY generated (stored SSH keys are encrypted at rest)"
        fi
    else
        if [[ -z "$AUTH_TOKEN" ]]; then
            AUTH_TOKEN="$(random_hex 32)"
            GENERATED_AUTH_TOKEN=true
            info "Admin token generated (64 hex characters)"
        else
            info "Using the provided admin token"
        fi
        local data_key
        if [[ -n "$PREVIOUS_DATA_KEY" && -f "$DB_PATH" ]]; then
            data_key="$PREVIOUS_DATA_KEY"
            notice "Keeping the previous DATA_ENCRYPTION_KEY (the existing database is kept)"
        else
            data_key="$(random_hex 32)"
        fi
        mkdir -p "$(dirname "$ENV_FILE")"
        local new_env
        new_env="$(mktemp "${ENV_FILE}.XXXXXX")"     # 0600, O_EXCL: never follows a planted link
        render_env_file "$data_key" > "$new_env"
        mv -f "$new_env" "$ENV_FILE"
        info "Configuration written to ${ENV_FILE}"
    fi

    # TLS-related settings
    if [[ "$TLS_MODE" != "none" ]]; then
        local n
        n="$(env_disable_letsencrypt_tls "$ENV_FILE")"
        if (( n > 0 )); then
            notice "Commented out ${n} TLS_CERT/TLS_KEY line(s) pointing into /etc/letsencrypt (nginx terminates TLS now)"
        fi
    fi
    if [[ "$TLS_MODE" == "new" ]]; then
        env_set "$ENV_FILE" BIND_HOST 127.0.0.1
        env_set "$ENV_FILE" TRUST_PROXY loopback
        env_set "$ENV_FILE" PUBLIC_URL "https://${DOMAIN}"
        env_set "$ENV_FILE" HTTP_TUNNEL_URL_TEMPLATE "$(http_tunnel_template "$DOMAIN" "$WILDCARD_DIR")"
        info "TLS settings: BIND_HOST=127.0.0.1, TRUST_PROXY=loopback, PUBLIC_URL=https://${DOMAIN}"
    elif [[ "$TLS_MODE" == "existing" ]]; then
        if [[ -f "${LE_LIVE_DIR}/${DOMAIN}/fullchain.pem" ]]; then
            env_ensure "$ENV_FILE" BIND_HOST 127.0.0.1 || true
            env_ensure "$ENV_FILE" TRUST_PROXY loopback || true
            env_ensure "$ENV_FILE" PUBLIC_URL "https://${DOMAIN}" || true
            env_ensure "$ENV_FILE" HTTP_TUNNEL_URL_TEMPLATE "$(http_tunnel_template "$DOMAIN" "$WILDCARD_DIR")" || true
        else
            warn "nginx is configured for ${DOMAIN} but no certificate exists yet."
            warn "Obtain it with: sudo bash install-server.sh --upgrade --tls --domain ${DOMAIN} [--email you@example.com]"
        fi
    fi

    chown "${SERVICE_USER}:${SERVICE_USER}" "$ENV_FILE"
    chmod 0600 "$ENV_FILE"
}

# ─── Step 8: data directories + schema ───────────────────────────
prepare_data_dirs() {
    local d
    for d in "$DATA_DIR" "$USERMGR_SPOOL_DIR" "$LOG_DIR"; do
        if [[ -L "$d" ]]; then fail "${d} must not be a symlink"; fi
        mkdir -p "$d"
    done
    safe_chown "${SERVICE_USER}:${SERVICE_USER}" "$DATA_DIR"
    safe_chown "${SERVICE_USER}:${SERVICE_USER}" "$USERMGR_SPOOL_DIR"
    safe_chown "${SERVICE_USER}:${SERVICE_USER}" "$LOG_DIR"
    chmod 0700 "$DATA_DIR" "$USERMGR_SPOOL_DIR"
    chmod 0750 "$LOG_DIR"
    local f
    for f in "$DB_PATH" "${DB_PATH}-wal" "${DB_PATH}-shm" "${LOG_DIR}/tunnelvault.log"; do
        safe_chown "${SERVICE_USER}:${SERVICE_USER}" "$f"
    done
}

init_database() {
    local out
    if out="$(cd "${INSTALL_DIR}/backend" && runuser -u "$SERVICE_USER" -- env -i \
            PATH=/usr/local/bin:/usr/bin:/bin HOME=/nonexistent NODE_ENV=production DB_PATH="$DB_PATH" \
            "$NODE_BIN" -e "require('${INSTALL_DIR}/backend/src/database.js').close()" 2>&1)"; then
        info "Database schema ready at ${DB_PATH} (migrations applied by the backend)"
    else
        echo "$out" | tail -n 5 >&2
        fail "Database initialisation failed"
    fi
}

# ─── Step 9: legacy SSH gateway ──────────────────────────────────
reload_sshd() {
    local unit
    for unit in ssh.service sshd.service; do
        if systemctl cat "$unit" >/dev/null 2>&1; then
            systemctl try-reload-or-restart "$unit" && return 0
        fi
    done
    warn "Could not reload sshd — reload it manually"
}

configure_sshd() {
    local sshd_bin
    sshd_bin="$(command -v sshd || true)"
    if [[ -z "$sshd_bin" && -x /usr/sbin/sshd ]]; then sshd_bin=/usr/sbin/sshd; fi
    if [[ -z "$sshd_bin" || ! -f "$SSHD_CONF" ]]; then
        warn "OpenSSH server not found — legacy SSH gateway not configured"
        return 0
    fi
    local new backup
    new="$(mktemp)"
    sshd_config_with_block "$SSHD_CONF" > "$new"
    if cmp -s "$new" "$SSHD_CONF"; then
        rm -f "$new"
        skipped "SSH gateway configuration unchanged"
    else
        backup="$(mktemp)"
        cp -p "$SSHD_CONF" "$backup"
        cat "$new" > "$SSHD_CONF"
        rm -f "$new"
        if "$sshd_bin" -t >/dev/null 2>&1; then
            rm -f "$backup"
            info "SSH gateway configuration updated (Match User gw-*)"
            reload_sshd
        else
            cat "$backup" > "$SSHD_CONF"
            rm -f "$backup"
            warn "sshd rejected the gateway configuration — ${SSHD_CONF} restored, legacy gateway disabled"
            return 0
        fi
    fi

    # Existing gateway users: router as login shell (sshd runs ForceCommand through
    # it; /bin/false never worked) and membership of the sudo group for the helper.
    local user shell count=0
    while IFS=: read -r user shell; do
        [[ "$user" =~ ^gw-[A-Za-z0-9]{1,29}$ ]] || continue
        [[ "$(id -u "$user")" != "0" ]] || continue
        if [[ "$shell" == "${INSTALL_DIR}/ssh_router.sh" ]] && id -nG "$user" 2>/dev/null | tr ' ' '\n' | grep -qx "$GW_GROUP"; then
            continue
        fi
        usermod --shell "${INSTALL_DIR}/ssh_router.sh" --append --groups "$GW_GROUP" "$user" && count=$((count + 1))
    done < <(getent passwd | awk -F: '$1 ~ /^gw-/ { print $1 ":" $7 }')
    if (( count > 0 )); then info "Updated ${count} existing gateway user(s)"; fi
}

# ─── Step 10: systemd units ──────────────────────────────────────
install_units() {
    if [[ -f "${SYSTEMD_DIR}/tunnelvault-api.service" ]]; then
        systemctl disable --now tunnelvault-api.service >/dev/null 2>&1 || true
        rm -f "${SYSTEMD_DIR}/tunnelvault-api.service"
        notice "Removed tunnelvault-api.service left behind by the deprecated gateway/setup.sh"
    fi
    render_service_unit "$NODE_BIN"      | write_file "${SYSTEMD_DIR}/${SERVICE_NAME}.service" 0644 root:root || true
    render_usermgr_path_unit             | write_file "${SYSTEMD_DIR}/${USERMGR_UNIT}.path" 0644 root:root || true
    render_usermgr_service_unit          | write_file "${SYSTEMD_DIR}/${USERMGR_UNIT}.service" 0644 root:root || true
    systemctl daemon-reload
    systemctl enable "${SERVICE_NAME}.service" >/dev/null 2>&1
    systemctl enable --now "${USERMGR_UNIT}.path" >/dev/null 2>&1 \
        || warn "Could not start ${USERMGR_UNIT}.path — gateway users requested by the API will not be created"
    info "Units installed: ${SERVICE_NAME}.service, ${USERMGR_UNIT}.path/.service"
}

start_service() {
    systemctl restart "${SERVICE_NAME}.service" || true
    local host _
    host="$(env_get "$ENV_FILE" BIND_HOST)"
    if [[ -z "$host" || "$host" == "0.0.0.0" || "$host" == "::" ]]; then host="127.0.0.1"; fi
    if [[ "$host" == *:* ]]; then host="[${host}]"; fi
    for _ in $(seq 1 30); do
        if curl -fsS --max-time 2 -o /dev/null "http://${host}:${API_PORT}/api/health" 2>/dev/null; then
            info "Service is running and healthy"
            return 0
        fi
        systemctl is-failed --quiet "${SERVICE_NAME}.service" && break
        sleep 1
    done
    START_FAILED=true
    warn "The service did not become healthy. Check: journalctl -u ${SERVICE_NAME} -n 50"
    journalctl -u "$SERVICE_NAME" -n 10 --no-pager 2>/dev/null | sed 's/^/    /' || true
}

# ─── Step 11: signed auto-updater ────────────────────────────────
remove_updater_units() {
    systemctl disable --now "${UPDATER_UNIT}.timer" >/dev/null 2>&1 || true
    rm -f "${SYSTEMD_DIR}/${UPDATER_UNIT}.timer" "${SYSTEMD_DIR}/${UPDATER_UNIT}.service" "$UPDATER_SCRIPT"
    systemctl daemon-reload
}

# The client's signed updater (not its old git-pull one) reads the same update.conf
client_updater_installed() {
    [[ -f "${SYSTEMD_DIR}/${CLIENT_UPDATER_UNIT}.timer" && -f "$CLIENT_UPDATER_SCRIPT" ]] \
        && grep -q 'tv-updater-common' "$CLIENT_UPDATER_SCRIPT" 2>/dev/null
}

# /etc/tunnelvault holds the updater's trust anchor: root-owned, not group/world-writable
# (the updater refuses anything else). 0755 so the backend can read update.conf; the
# client's secrets in there (client.env) are 0600 on their own.
prepare_conf_dir() {
    if [[ -L "$CONF_DIR" || ( -e "$CONF_DIR" && ! -d "$CONF_DIR" ) ]]; then
        warn "${CONF_DIR} is a symlink or not a directory — refusing to write the updater configuration there"
        return 1
    fi
    if [[ -L "$UPDATE_CONF" || -L "$INSTALLED_PUBKEY" ]]; then
        warn "${UPDATE_CONF} or ${INSTALLED_PUBKEY} is a symlink — refusing to use it"
        return 1
    fi
    mkdir -p "$CONF_DIR"
    chown root:root "$CONF_DIR"
    chmod 0755 "$CONF_DIR"
}

configure_updater() {
    local legacy=false installed_before=false shared=false action conf_enabled
    is_legacy_updater "$UPDATER_SCRIPT" && legacy=true
    conf_enabled="$(env_get "$UPDATE_CONF" ENABLED)"
    if ! $legacy && [[ -f "${SYSTEMD_DIR}/${UPDATER_UNIT}.timer" && -f "$UPDATER_SCRIPT" ]]; then
        installed_before=true
    fi
    client_updater_installed && shared=true

    if [[ "$AUTO_UPDATE" == "yes" ]]; then
        action="install"
    elif [[ "$AUTO_UPDATE" == "no" ]]; then
        action="disable"
    elif $UPGRADE && $installed_before; then
        action="install"          # keep the previous choice (also while paused with ENABLED=0)
    else
        action="none"
    fi

    if [[ "$action" == "install" ]]; then
        if [[ ! -f "${SCRIPT_DIR}/auto-update.sh" ]] || is_legacy_updater "${SCRIPT_DIR}/auto-update.sh"; then
            warn "This source tree has no signed updater (auto-update.sh) — auto-update not installed"
            action="none"
        fi
        resolve_pubkey_source
        if [[ -z "$PUBKEY_SOURCE" ]]; then
            warn "No release public key available — auto-update not installed"
            action="none"
        elif ! is_p256_pubkey "$PUBKEY_SOURCE"; then
            warn "${PUBKEY_SOURCE} is not an ECDSA P-256 public key — auto-update not installed"
            action="none"
        fi
        if [[ "$action" == "install" ]] && ! prepare_conf_dir; then action="none"; fi
    fi

    case "$action" in
        install)
            if [[ "$PUBKEY_SOURCE" != "$INSTALLED_PUBKEY" ]]; then
                if [[ -f "$INSTALLED_PUBKEY" && -z "$RELEASE_PUBKEY_ARG" ]]; then
                    : # never replace the trust anchor implicitly
                else
                    write_file "$INSTALLED_PUBKEY" 0644 root:root < "$PUBKEY_SOURCE" && info "Release public key installed at ${INSTALLED_PUBKEY}"
                fi
            fi
            chown root:root "$INSTALLED_PUBKEY"; chmod 0644 "$INSTALLED_PUBKEY"
            if [[ -f "${SCRIPT_DIR}/release-signing.pub" ]] && ! cmp -s "${SCRIPT_DIR}/release-signing.pub" "$INSTALLED_PUBKEY"; then
                notice "release-signing.pub of this package differs from ${INSTALLED_PUBKEY} (kept). Use --release-pubkey to replace it."
            fi
            if [[ -f "$UPDATE_CONF" ]]; then
                # keep ENABLED (unless --auto-update), UPDATE_REPO, PINNED_VERSION and SCHEDULE
                [[ "$AUTO_UPDATE" == "yes" ]] && env_set "$UPDATE_CONF" ENABLED 1
                env_ensure "$UPDATE_CONF" SCHEDULE "$DEFAULT_UPDATE_SCHEDULE" || true
                env_ensure "$UPDATE_CONF" UPDATE_REPO "$DEFAULT_UPDATE_REPO" || true
                env_ensure "$UPDATE_CONF" PINNED_VERSION "" || true
                env_ensure "$UPDATE_CONF" PUBKEY "$INSTALLED_PUBKEY" || true
                chown root:root "$UPDATE_CONF"; chmod 0644 "$UPDATE_CONF"
            else
                render_update_conf 1 | write_file "$UPDATE_CONF" 0644 root:root || true
            fi
            write_file "$UPDATER_SCRIPT" 0755 root:root < "${SCRIPT_DIR}/auto-update.sh" || true
            render_updater_service_unit | write_file "${SYSTEMD_DIR}/${UPDATER_UNIT}.service" 0644 root:root || true
            render_updater_timer_unit "$(env_get "$UPDATE_CONF" SCHEDULE)" \
                | write_file "${SYSTEMD_DIR}/${UPDATER_UNIT}.timer" 0644 root:root || true
            systemctl daemon-reload
            systemctl enable --now "${UPDATER_UNIT}.timer" >/dev/null 2>&1 || warn "Could not enable ${UPDATER_UNIT}.timer"
            if $legacy; then
                notice "The old unsigned git-pull updater was replaced by the signed release updater"
            fi
            local schedule
            schedule="$(env_get "$UPDATE_CONF" SCHEDULE)"
            is_valid_schedule "$schedule" || schedule="$DEFAULT_UPDATE_SCHEDULE"
            if is_enabled_value "$(env_get "$UPDATE_CONF" ENABLED)"; then
                UPDATER_STATE="enabled (signed releases, every ${schedule})"
                info "Signed auto-updater enabled (every ${schedule}; key ${INSTALLED_PUBKEY}; settings ${UPDATE_CONF})"
            else
                UPDATER_STATE="installed but paused (ENABLED=0 in ${UPDATE_CONF})"
                warn "Signed auto-updater installed but paused: ENABLED=0 in ${UPDATE_CONF} (kept). Resume with --upgrade --auto-update."
            fi
            ;;
        disable)
            remove_updater_units
            if [[ -f "$UPDATE_CONF" && ! -L "$UPDATE_CONF" ]]; then
                if $shared; then
                    notice "${UPDATE_CONF} is shared with the client auto-updater on this host — ENABLED left unchanged there"
                else
                    env_set "$UPDATE_CONF" ENABLED 0
                fi
            fi
            $legacy && notice "The old unsigned git-pull updater was removed"
            UPDATER_STATE="disabled"
            info "Auto-updater disabled"
            ;;
        none)
            if $legacy; then
                remove_updater_units
                warn "Removed the old auto-updater: it ran 'git pull' as root without any verification."
            elif [[ -f "${SYSTEMD_DIR}/${UPDATER_UNIT}.timer" && ! -f "$UPDATER_SCRIPT" ]]; then
                remove_updater_units
                notice "Removed an orphaned ${UPDATER_UNIT}.timer (${UPDATER_SCRIPT} was missing)"
            fi
            if [[ -f "${SYSTEMD_DIR}/${UPDATER_UNIT}.timer" ]] && ! $legacy; then
                UPDATER_STATE="installed (not changed by this run)"
            elif [[ "$AUTO_UPDATE" == "yes" || "$conf_enabled" != "0" ]]; then
                UPDATER_STATE="not installed"
                notice "Signed auto-updates are off. Enable with:"
                notice "  sudo bash install-server.sh --upgrade --auto-update --release-pubkey /path/to/release-signing.pub"
            else
                UPDATER_STATE="disabled"
                skipped "Auto-updater disabled (${UPDATE_CONF})"
            fi
            ;;
    esac
    if $shared && [[ "$action" == "install" ]]; then
        notice "${UPDATE_CONF} is shared with the client auto-updater on this host: ENABLED=0 pauses both,"
        notice "UPDATE_REPO, PINNED_VERSION and SCHEDULE apply to both (each keeps its own timer)."
    fi
}

# ─── Step 12: firewall ───────────────────────────────────────────
firewall_rules() {
    # "port/proto|comment" lines
    if [[ "$TLS_MODE" != "none" ]]; then
        echo "80/tcp|TunnelVault HTTP (ACME, redirects, HTTP tunnels)"
        echo "443/tcp|TunnelVault HTTPS"
    else
        echo "${API_PORT}/tcp|TunnelVault API + dashboard"
        echo "${PROXY_PORT}/tcp|TunnelVault HTTP tunnel proxy"
    fi
    echo "${TCP_PORT_MIN}:${TCP_PORT_MAX}/tcp|TunnelVault TCP tunnels"
}

ssh_ports() {
    local p
    {
        echo 22
        if command -v sshd >/dev/null 2>&1; then
            sshd -T 2>/dev/null | awk '$1 == "port" { print $2 }'
        fi
    } | while read -r p; do is_valid_port "$p" && echo "$p"; done | sort -un
}

configure_firewall() {
    local rules spec comment status
    rules="$(firewall_rules)"
    if $NO_FIREWALL; then
        skipped "Firewall (--no-firewall). Allow inbound: $(cut -d'|' -f1 <<< "$rules" | tr '\n' ' ')"
        return 0
    fi
    if systemctl is-active --quiet firewalld 2>/dev/null; then
        warn "firewalld is active — not touching it. Allow inbound: $(cut -d'|' -f1 <<< "$rules" | tr '\n' ' ')"
        return 0
    fi
    if ! command -v ufw >/dev/null 2>&1; then
        if $UPGRADE; then
            skipped "ufw not installed. Allow inbound: $(cut -d'|' -f1 <<< "$rules" | tr '\n' ' ')"
            return 0
        fi
        apt_install ufw
    fi
    status="$(ufw status 2>/dev/null | head -n 1 || true)"
    if [[ "$status" != "Status: active" ]]; then
        if $UPGRADE; then
            warn "ufw is inactive — not enabling it during an upgrade. Allow inbound: $(cut -d'|' -f1 <<< "$rules" | tr '\n' ' ')"
            return 0
        fi
        ufw default deny incoming >/dev/null
        ufw default allow outgoing >/dev/null
        local p
        for p in $(ssh_ports); do
            ufw allow "${p}/tcp" comment "SSH" >/dev/null
            info "Allowed ${p}/tcp (SSH)"
        done
    fi
    while IFS='|' read -r spec comment; do
        [[ -n "$spec" ]] || continue
        ufw allow "$spec" comment "$comment" >/dev/null
        info "Allowed ${spec} (${comment})"
    done <<< "$rules"
    if [[ "$status" != "Status: active" ]]; then
        ufw --force enable >/dev/null
        info "Firewall enabled (default: deny incoming)"
    else
        info "Firewall already active — existing rules kept"
    fi
    if [[ "$TLS_MODE" != "none" ]] && ufw status 2>/dev/null | grep -Eq "^(${API_PORT}|${PROXY_PORT})/tcp"; then
        notice "Ports ${API_PORT}/${PROXY_PORT} are still allowed from an older install; TunnelVault now listens on 127.0.0.1 only."
        notice "Remove with: ufw delete allow ${API_PORT}/tcp && ufw delete allow ${PROXY_PORT}/tcp"
    fi
}

# ─── Step 13: nginx + Let's Encrypt ──────────────────────────────
nginx_reload() {
    systemctl enable nginx >/dev/null 2>&1 || true
    if systemctl is-active --quiet nginx; then systemctl reload nginx; else systemctl restart nginx; fi
}

# install_nginx_conf CONTENT_FILE: install, test, roll back on failure
install_nginx_conf() {
    local content="$1" site_file backup="" ts
    site_file="$(nginx_site_file)"
    if [[ -f "$site_file" ]] && cmp -s "$content" "$site_file"; then
        if [[ "$site_file" == */sites-available/* && ! -e "${NGINX_DIR}/sites-enabled/tunnelvault" ]]; then
            ln -sfn "$site_file" "${NGINX_DIR}/sites-enabled/tunnelvault"
            nginx -t >/dev/null 2>&1 && nginx_reload
        fi
        return 0
    fi
    if [[ -f "$site_file" ]]; then
        ts="$(date -u '+%Y%m%d-%H%M%S')"
        mkdir -p "$BACKUP_DIR"; chmod 0700 "$BACKUP_DIR"
        backup="${BACKUP_DIR}/nginx-tunnelvault.${ts}.conf"
        cp -p "$site_file" "$backup"
    fi
    write_file "$site_file" 0644 root:root < "$content" || true
    if [[ "$site_file" == */sites-available/* ]]; then
        mkdir -p "${NGINX_DIR}/sites-enabled"
        ln -sfn "$site_file" "${NGINX_DIR}/sites-enabled/tunnelvault"
    fi
    if nginx -t >/dev/null 2>&1; then
        nginx_reload
        return 0
    fi
    nginx -t 2>&1 | tail -n 3 | sed 's/^/    /' >&2 || true
    if [[ -n "$backup" ]]; then
        cp -p "$backup" "$site_file"
    else
        rm -f "$site_file" "${NGINX_DIR}/sites-enabled/tunnelvault"
    fi
    return 1
}

configure_tls() {
    local site_file content ipv6=0 h2=0 ver cert="${LE_LIVE_DIR}/${DOMAIN}/fullchain.pem"
    site_file="$(nginx_site_file)"
    if [[ "$TLS_MODE" == "existing" && -f "$site_file" ]] && ! nginx_conf_is_ours "$site_file"; then
        skipped "nginx configuration was customised (marker removed) — left unchanged"
        return 0
    fi
    apt_install nginx certbot
    [[ -f /proc/net/if_inet6 ]] && ipv6=1
    ver="$(nginx -v 2>&1 | sed -n 's|.*nginx/\([0-9.]*\).*|\1|p')"
    if [[ -n "$ver" ]] && version_ge "$ver" "1.25.1"; then h2=1; fi

    mkdir -p "$ACME_WEBROOT"; chmod 0755 "$ACME_WEBROOT"
    render_deploy_hook | write_file "$DEPLOY_HOOK" 0755 root:root || true
    content="$(mktemp)"

    if [[ ! -f "$cert" ]]; then
        if [[ "$TLS_MODE" == "existing" ]]; then
            warn "No certificate for ${DOMAIN} yet — obtain it with:"
            warn "  sudo bash install-server.sh --upgrade --tls --domain ${DOMAIN} [--email you@example.com]"
            rm -f "$content"
            return 0
        fi
        render_nginx_conf acme "$DOMAIN" "$API_PORT" "$PROXY_PORT" "" "$ipv6" "$h2" > "$content"
        if ! install_nginx_conf "$content"; then
            rm -f "$content"; TLS_FAILED=true
            warn "nginx rejected the temporary ACME configuration"
            return 0
        fi
        info "nginx answers ACME challenges for ${DOMAIN}"
        local email_args=(--register-unsafely-without-email)
        [[ -n "$TLS_EMAIL" ]] && email_args=(--email "$TLS_EMAIL")
        echo "  ${DIM}Requesting a Let's Encrypt certificate for ${DOMAIN} (HTTP-01)...${NC}"
        if ! certbot certonly --webroot -w "$ACME_WEBROOT" -d "$DOMAIN" --cert-name "$DOMAIN" \
                --non-interactive --agree-tos --keep-until-expiring "${email_args[@]}" 2>&1 | tail -n 5 | sed 's/^/    /' \
            || [[ ! -f "$cert" ]]; then
            rm -f "$content"; TLS_FAILED=true
            warn "certbot could not obtain a certificate. Check that ${DOMAIN} resolves to this server and"
            warn "port 80 is reachable, then re-run: sudo bash install-server.sh --upgrade --tls --domain ${DOMAIN}"
            return 0
        fi
        info "Certificate obtained (renewed automatically by certbot; nginx reloads via ${DEPLOY_HOOK})"
    fi

    render_nginx_conf https "$DOMAIN" "$API_PORT" "$PROXY_PORT" "$WILDCARD_DIR" "$ipv6" "$h2" > "$content"
    if install_nginx_conf "$content"; then
        TLS_OK=true
        info "nginx serves https://${DOMAIN} (dashboard, API, /ws, /ws/ssh)"
        if [[ -n "$WILDCARD_DIR" ]]; then
            info "HTTP tunnels: https://<subdomain>.${DOMAIN}"
        else
            notice "HTTP tunnels: http://<subdomain>.${DOMAIN} (plain HTTP; add --wildcard-cert DIR for HTTPS)"
        fi
    else
        [[ "$TLS_MODE" == "new" ]] && TLS_FAILED=true
        warn "nginx rejected the generated configuration — previous configuration restored"
    fi
    rm -f "$content"
}

# ─── Summary ─────────────────────────────────────────────────────
print_summary() {
    local host status
    status="$(systemctl is-active "$SERVICE_NAME" 2>/dev/null || true)"
    host="$(hostname -I 2>/dev/null | awk '{ print $1 }')"
    host="${host:-<server-ip>}"
    echo ""
    if $UPGRADE; then
        echo "${BOLD}${GREEN}  TunnelVault ${SOURCE_VERSION} — upgrade finished${NC}"
    else
        echo "${BOLD}${GREEN}  TunnelVault ${SOURCE_VERSION} — installation finished${NC}"
    fi
    echo "  ────────────────────────────────────────────────────"
    if $TLS_OK; then
        echo "  Dashboard:       ${CYAN}https://${DOMAIN}${NC}"
        echo "  Device server:   ${CYAN}wss://${DOMAIN}${NC}"
    else
        echo "  Dashboard:       ${CYAN}http://${host}:${API_PORT}${NC}   ${RED}(plaintext)${NC}"
        echo "  Device server:   ${CYAN}ws://${host}:${API_PORT}${NC}"
    fi
    echo "  TCP tunnels:     ports ${TCP_PORT_MIN}-${TCP_PORT_MAX}"
    echo "  Service:         ${status:-unknown}"
    echo "  Auto-update:     ${UPDATER_STATE}"
    if [[ -f "${SYSTEMD_DIR}/${UPDATER_UNIT}.timer" && -f "$UPDATER_SCRIPT" ]] && ! is_legacy_updater "$UPDATER_SCRIPT"; then
        echo "                   settings ${UPDATE_CONF}, key ${INSTALLED_PUBKEY}"
        echo "                   logs: journalctl -u ${UPDATER_UNIT} and ${UPDATER_LOG}"
        echo "                   run now: sudo ${UPDATER_SCRIPT} [--dry-run]"
    fi
    echo "  Config:          ${ENV_FILE}"
    echo "  Database:        ${DB_PATH}"
    echo "  Logs:            journalctl -u ${SERVICE_NAME} -f   (${LOG_DIR}/)"
    echo "  Gateway logs:    journalctl -t tunnelvault-gateway -t ${USERMGR_UNIT}"
    if $GENERATED_AUTH_TOKEN; then
        echo ""
        echo "  ${BOLD}${YELLOW}Admin token (log in to the dashboard with it; stored in ${ENV_FILE}):${NC}"
        echo "  ${BOLD}${AUTH_TOKEN}${NC}"
    elif ! $UPGRADE; then
        echo "  Admin token:     the one given with --auth-token (stored in ${ENV_FILE})"
    fi
    if ! $TLS_OK; then
        print_plaintext_warning
    fi
    if $TLS_FAILED; then
        echo "  ${RED}TLS setup did not complete — see the warnings above.${NC}"
    fi
    if $START_FAILED; then
        echo "  ${RED}The service is not healthy — see: journalctl -u ${SERVICE_NAME} -n 50${NC}"
    fi
    echo ""
}

# ================================================================
main() {
    parse_args "$@"
    if $ENABLE_TLS || { $UPGRADE && nginx_conf_is_ours "$(nginx_site_file)"; }; then TOTAL_STEPS=14; fi

    echo ""
    echo "${BOLD}${CYAN}  TunnelVault Server Installer${NC}"
    if $UPGRADE; then echo "  ${YELLOW}Mode: upgrade${NC}"; else echo "  ${DIM}Mode: install${NC}"; fi

    step "Pre-flight checks"
    preflight
    if [[ "$TLS_MODE" == "none" ]]; then print_plaintext_warning; fi

    step "System packages"
    apt-get update -qq >/dev/null || warn "apt-get update reported errors"
    apt_install sqlite3 netcat-openbsd curl ca-certificates gnupg openssl sudo util-linux

    step "Node.js (>= ${MIN_NODE_MAJOR})"
    ensure_node

    step "Service user and groups"
    ensure_users

    step "Preparing application (staging)"
    prepare_application

    step "Installing application files"
    if $UPGRADE && systemctl is-active --quiet "${SERVICE_NAME}.service"; then
        systemctl stop "${SERVICE_NAME}.service"
        info "Service stopped for the upgrade"
    fi
    swap_in_application
    install_gateway_files

    step "Configuration"
    configure_env

    step "Database"
    prepare_data_dirs
    init_database

    step "Legacy SSH gateway"
    configure_sshd

    step "systemd units"
    install_units

    step "Starting TunnelVault"
    start_service

    step "Signed auto-updates"
    configure_updater

    step "Firewall"
    configure_firewall

    if [[ "$TLS_MODE" != "none" ]]; then
        step "nginx + Let's Encrypt"
        configure_tls
    fi

    print_summary
    if $START_FAILED || $TLS_FAILED; then exit 1; fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
